import React, { useState } from 'react';
import { Plus, Check, Trash2, Printer, Clipboard } from 'lucide-react';
import { VISIT_QUESTION_TEMPLATES as templates } from '../utils/mockData';

export const VisitPrep: React.FC = () => {
  const [selectedSpecialty, setSelectedSpecialty] = useState(templates[0].specialty);
  const [customConcern, setCustomConcern] = useState('');
  const [customQuestion, setCustomQuestion] = useState('');
  const [customQuestionsList, setCustomQuestionsList] = useState<string[]>([]);
  const [selectedTemplateQuestions, setSelectedTemplateQuestions] = useState<string[]>(
    templates[0].suggestedQuestions
  );
  const [activeQuestions, setActiveQuestions] = useState<string[]>(
    [...templates[0].suggestedQuestions]
  );
  const [lovedOneName, setLovedOneName] = useState('Arthur');

  const handleSpecialtyChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const spec = e.target.value;
    setSelectedSpecialty(spec);
    
    const matched = templates.find(t => t.specialty === spec);
    const suggested = matched ? matched.suggestedQuestions : [];
    setSelectedTemplateQuestions(suggested);
    // Reset combined active questions list
    setActiveQuestions([...suggested, ...customQuestionsList]);
  };

  const handleToggleQuestion = (q: string) => {
    setActiveQuestions(prev =>
      prev.includes(q) ? prev.filter(item => item !== q) : [...prev, q]
    );
  };

  const handleAddCustomQuestion = (e: React.FormEvent) => {
    e.preventDefault();
    if (!customQuestion.trim()) return;
    
    const q = customQuestion.trim();
    setCustomQuestionsList(prev => [...prev, q]);
    setActiveQuestions(prev => [...prev, q]);
    setCustomQuestion('');
  };

  const handleDeleteCustomQuestion = (q: string) => {
    setCustomQuestionsList(prev => prev.filter(item => item !== q));
    setActiveQuestions(prev => prev.filter(item => item !== q));
  };

  const handlePrint = () => {
    window.print();
  };

  const handleCopyToClipboard = () => {
    const text = `SURGEON FOLLOW-UP PREPARATION CHECKLIST
Patient: ${lovedOneName}
Specialty: ${selectedSpecialty}
Recovery Concerns: ${customConcern || 'None listed'}

QUESTIONS TO ASK THE SURGICAL TEAM:
${activeQuestions.map((q, idx) => `${idx + 1}. ${q}`).join('\n')}

Generated by Shalom AI - Post-Operative Recovery Assistant.`;

    navigator.clipboard.writeText(text);
    alert('Surgeon follow-up checklist copied to clipboard!');
  };

  return (
    <div className="tool-card print-container">
      <div className="tool-header no-print">
        <div>
          <h2>Surgeon Follow-Up Prep Assistant</h2>
          <p className="tool-subtitle">Build a checklist of questions to ask your surgeon or clinical care team at your follow-up appointment.</p>
        </div>
      </div>

      <div className="prep-layout">
        {/* Setup Panel */}
        <div className="prep-panel setup-panel no-print">
          <h3>1. Prepare Details</h3>
          
          <div className="form-group">
            <label>Patient's Name</label>
            <input
              type="text"
              value={lovedOneName}
              onChange={e => setLovedOneName(e.target.value)}
              placeholder="e.g., Arthur"
            />
          </div>

          <div className="form-group">
            <label>Surgery Type / Specialty</label>
            <select value={selectedSpecialty} onChange={handleSpecialtyChange}>
              {templates.map(t => (
                <option key={t.specialty} value={t.specialty}>
                  {t.specialty}
                </option>
              ))}
            </select>
          </div>

          <div className="form-group">
            <label>Specific Recovery Concerns (Incisions, pain levels, physical therapy limits)</label>
            <textarea
              rows={4}
              placeholder="e.g., Redness around incision spreading slightly. Pain level has gone up to 5/10. Mild stomach upset after taking Oxycodone."
              value={customConcern}
              onChange={e => setCustomConcern(e.target.value)}
            />
          </div>

          <form onSubmit={handleAddCustomQuestion} className="custom-q-form">
            <label>Add a Custom Question</label>
            <div className="input-with-button-row">
              <input
                type="text"
                placeholder="e.g., Should we schedule physical therapy?"
                value={customQuestion}
                onChange={e => setCustomQuestion(e.target.value)}
              />
              <button type="submit" className="btn-secondary">
                <Plus size={16} />
              </button>
            </div>
          </form>
        </div>

        {/* Builder / Review Panel */}
        <div className="prep-panel questions-builder-panel">
          <div className="review-header">
            <h3>2. Customize Questions Checklist</h3>
            <div className="action-buttons-row no-print">
              <button className="btn-secondary btn-icon-only" onClick={handleCopyToClipboard} title="Copy to clipboard">
                <Clipboard size={16} />
              </button>
              <button className="btn-secondary btn-icon-only" onClick={handlePrint} title="Print Checklist">
                <Printer size={16} />
              </button>
            </div>
          </div>

          {/* Printable Document View */}
          <div className="printable-document">
            <div className="doc-banner">
              <div>
                <span className="doc-logo-sub">Shalom AI Post-Op Assistant</span>
                <h1 className="doc-title">Surgeon Follow-Up Prep Sheet</h1>
              </div>
              <div className="doc-date">Date: _________________</div>
            </div>

            <div className="doc-meta-grid">
              <div><strong>Patient:</strong> {lovedOneName}</div>
              <div><strong>Specialist Type:</strong> {selectedSpecialty}</div>
              <div className="full-width">
                <strong>Recent Recovery Concerns & Notes:</strong>
                <p className="doc-notes-paragraph">{customConcern || "No special concerns noted yet. Enter details in the concern box to display."}</p>
              </div>
            </div>

            <div className="doc-section-title">Selected Questions for the Surgeon:</div>
            
            {/* Interactive check list in app, printable as bullet circles */}
            <div className="doc-questions-list">
              {/* Template suggested questions */}
              {selectedTemplateQuestions.map((q, idx) => {
                const isActive = activeQuestions.includes(q);
                return (
                  <div 
                    key={`temp-${idx}`} 
                    className={`doc-q-item no-print-interactive ${isActive ? '' : 'inactive-q no-print'}`}
                    onClick={() => handleToggleQuestion(q)}
                  >
                    <div className={`doc-checkbox ${isActive ? 'checked' : ''}`}>
                      {isActive && <Check size={12} />}
                    </div>
                    <span className="q-text">{q}</span>
                  </div>
                );
              })}

              {/* Custom questions */}
              {customQuestionsList.map((q, idx) => {
                const isActive = activeQuestions.includes(q);
                return (
                  <div key={`cust-${idx}`} className="doc-q-item custom-q-item">
                    <div 
                      className={`doc-checkbox ${isActive ? 'checked' : ''}`}
                      onClick={() => handleToggleQuestion(q)}
                    >
                      {isActive && <Check size={12} />}
                    </div>
                    <span className="q-text">{q}</span>
                    <button 
                      className="delete-q-btn no-print" 
                      onClick={(e) => {
                        e.stopPropagation();
                        handleDeleteCustomQuestion(q);
                      }}
                    >
                      <Trash2 size={14} />
                    </button>
                  </div>
                );
              })}
            </div>
            
            <div className="doc-notes-lines print-only">
              <div className="doc-section-title">Surgeon's Answers & Decisions:</div>
              <div className="write-line"></div>
              <div className="write-line"></div>
              <div className="write-line"></div>
              <div className="write-line"></div>
              <div className="write-line"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
